name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # This triggers the workflow when a pull request is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner operating system

    steps:
    # Step 1: Check out the code from your GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password (token)

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/llm-inference-image .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/llm-inference-image
